kind: pipeline
type: exec
name: default

steps:

- name: build
  commands:
  - sudo docker build . -t kodapostle-blog:${DRONE_BUILD_NUMBER}
  when:
    branch:
    - main

- name: deploy
  commands:
  - sudo docker container stop blog
  - sudo docker container remove blog
  - sudo docker run --name blog -d  -p 4000:4000 kodapostle-blog:${DRONE_BUILD_NUMBER}
  when:
    branch:
    - main
